---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  playbook: tests/default.yml
  hosts: all
  require_ansible_repo: true
  #require_ansible_omnibus: true
  # this version doesn't have ansible-playbook binary by some reason
  #ansible_version: 2.2.0
  #idempotency_test true

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu
  #- name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
