---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  # TODO: make circle ci working with default.yml playbook
  playbook: tests/default.yml
  hosts: all
  require_ansible_repo: true
  ansible_verbose: true
  #require_ansible_omnibus: true
  # this version doesn't have ansible-playbook binary by some reason
  #ansible_version: 2.2.0
  idempotency_test: true
  require_chef_for_busser: false

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu
  - name: centos-7.2
  # TODO: add and fix
  # - name: amazonlinux
  #   driver_config:
  #     image: amazonlinux:2018.03
  #     platform: rhel

suites:
  - name: default
