---
- name: Install any necessary dependencies [Debian/Ubuntu]
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - alien
  when: ansible_os_family == "Debian"

- name: get telegraf rpm
  shell: "aws s3 cp {{telegraf_install_s3_path}} /tmp/telegraf.rpm"

- name: install rpm [Debian/Ubuntu]
  shell: alien -i /tmp/telegraf.rpm
  when: ansible_os_family == "Debian"

- name: install rpm [RedHat/CentOS]
  shell: rpm -i /tmp/telegraf.rpm
  when: ansible_os_family == "RedHat"
