---
- include: install-redhat.yml
  when: telegraf_install_s3_path == "" and ansible_os_family == "RedHat"

- include: install-debian.yml
  when: telegraf_install_s3_path == "" and ansible_os_family == "Debian"

- include: install-rpm.yml
  when: telegraf_install_s3_path != ""